alias ls='ls -F --color --show-control-chars'
alias ll='ls -lah'
alias r='rm -rf'
alias gs='git status -sb'
alias ga='git add'
alias gc='git commit'
alias gch='git checkout'
alias gp='git pull'
alias gpp='git push'
alias gpo='git push origin'
alias gr='git reset --hard'
alias gbr='git branch && git remote'
alias com='composer'
alias cu='composer update'
alias csu='composer self-update'
alias ci='composer install'
alias cda='composer dump-autoload --optimize'
alias lint='php -l'
alias sf='php app/console'
alias prod='php app/console --env=prod'
alias dev='php app/console --env=dev'
alias cache='php app/console cache:clear'
alias ..="cd .."
alias ...="cd ../.."
alias g='git'
alias c='composer'
alias p='php'
alias h='cd ~'
alias c='clear'
alias v='vagrant'
alias vgi='vagrant init'
alias vu='vagrant up'
alias vs='vagrant ssh'
echo ''
echo 'Welcome to the terminal of Michael!!!'
echo '============================================'
echo ''
echo 'Aliases:'
echo '--------'
echo 'll, c [clear], h [cd ~], r [rm -rf]'
echo 'g [git], gs, ga, gc, gch [checkout], gp, gpp/gpo [push], gr [reset], gbr [branch && remote]'
echo 'com [composer], cu [update], csu [self-update], ci [install], cda [dump-autoload]'
echo 'p [php], lint, sf, prod, dev, cache'
echo 'v [vagrant], vgi [init], vu [up], vs [ssh]'
